# Generated by Django 4.2.4 on 2024-08-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbTimelineDados',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('ciclo', models.IntegerField(db_column='ciclo')),
                ('chave', models.CharField(max_length=45)),
                ('valor', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'db_timeline_dados',
                'managed': True,
                'unique_together': {('ciclo', 'chave')},
            },
        ),
        migrations.CreateModel(
            name='DbTimeline_sensores',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('ciclo', models.IntegerField(db_column='ciclo')),
                ('evento', models.CharField(db_column='evento', max_length=45)),
                ('datetime', models.DateTimeField(db_column='datetime')),
                ('carro', models.CharField(db_column='carro', max_length=2)),
                ('status', models.BooleanField(db_column='status')),
            ],
            options={
                'db_table': 'db_timeline_sensores',
                'managed': True,
                'unique_together': {('ciclo', 'evento', 'datetime', 'carro', 'status')},
            },
        ),
        migrations.CreateModel(
            name='DbTimeline',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('ciclo', models.IntegerField(db_column='ciclo')),
                ('evento', models.CharField(db_column='evento', max_length=45)),
                ('datetime', models.DateTimeField(db_column='datetime')),
                ('carro', models.CharField(db_column='carro', max_length=2)),
            ],
            options={
                'db_table': 'db_timeline',
                'managed': True,
                'unique_together': {('ciclo', 'evento', 'datetime')},
            },
        ),
    ]
