# Generated by Django 4.2.4 on 2024-08-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allevent',
            fields=[
                ('eventid', models.CharField(db_column='EventID', max_length=36, primary_key=True, serialize=False)),
                ('machineid', models.CharField(blank=True, db_column='MachineID', max_length=50, null=True)),
                ('eventtype', models.IntegerField(blank=True, db_column='EventType', null=True)),
                ('sourcename', models.CharField(blank=True, db_column='SourceName', max_length=200, null=True)),
                ('sourcepath', models.CharField(blank=True, db_column='SourcePath', max_length=512, null=True)),
                ('sourceid', models.CharField(blank=True, db_column='SourceID', max_length=36, null=True)),
                ('servername', models.CharField(blank=True, db_column='ServerName', max_length=50, null=True)),
                ('tickstimestamp', models.BigIntegerField(blank=True, db_column='TicksTimeStamp', null=True)),
                ('eventtimestamp', models.DateTimeField(blank=True, db_column='EventTimeStamp', null=True)),
                ('eventcategory', models.CharField(blank=True, db_column='EventCategory', max_length=50, null=True)),
                ('severity', models.IntegerField(blank=True, db_column='Severity', null=True)),
                ('priority', models.IntegerField(blank=True, db_column='Priority', null=True)),
                ('message', models.CharField(blank=True, db_column='Message', max_length=512, null=True)),
                ('conditionname', models.CharField(blank=True, db_column='ConditionName', max_length=50, null=True)),
                ('subconditionname', models.CharField(blank=True, db_column='SubConditionName', max_length=50, null=True)),
                ('alarmclass', models.CharField(blank=True, db_column='AlarmClass', max_length=40, null=True)),
                ('active', models.CharField(blank=True, db_column='Active', max_length=50, null=True)),
                ('acked', models.IntegerField(blank=True, db_column='Acked', null=True)),
                ('effdisabled', models.IntegerField(blank=True, db_column='EffDisabled', null=True)),
                ('disabled', models.IntegerField(blank=True, db_column='Disabled', null=True)),
                ('effsuppressed', models.IntegerField(blank=True, db_column='EffSuppressed', null=True)),
                ('suppressed', models.CharField(blank=True, db_column='Suppressed', max_length=6, null=True)),
                ('personid', models.CharField(blank=True, db_column='PersonID', max_length=50, null=True)),
                ('changemask', models.IntegerField(blank=True, db_column='ChangeMask', null=True)),
                ('inputvalue', models.FloatField(blank=True, db_column='InputValue', null=True)),
                ('limitvalue', models.FloatField(blank=True, db_column='LimitValue', null=True)),
                ('quality', models.IntegerField(blank=True, db_column='Quality', null=True)),
                ('eventassociationid', models.CharField(blank=True, db_column='EventAssociationID', max_length=36, null=True)),
                ('usercomment', models.CharField(blank=True, db_column='UserComment', max_length=512, null=True)),
                ('computerid', models.CharField(blank=True, db_column='ComputerID', max_length=64, null=True)),
                ('tag1value', models.CharField(blank=True, db_column='Tag1Value', max_length=128, null=True)),
                ('tag2value', models.CharField(blank=True, db_column='Tag2Value', max_length=128, null=True)),
                ('tag3value', models.CharField(blank=True, db_column='Tag3Value', max_length=128, null=True)),
                ('tag4value', models.CharField(blank=True, db_column='Tag4Value', max_length=128, null=True)),
                ('shelved', models.CharField(blank=True, db_column='Shelved', max_length=6, null=True)),
                ('autounshelvetime', models.DateTimeField(blank=True, db_column='AutoUnshelveTime', null=True)),
                ('grouppath', models.CharField(blank=True, db_column='GroupPath', max_length=254, null=True)),
                ('messageid', models.CharField(blank=True, db_column='MessageID', max_length=254, null=True)),
                ('datetime', models.DateTimeField(db_column='datetime')),
            ],
            options={
                'db_table': 'events',
                'permissions': (('dashboard', 'User pode visualizar dashboard'), ('api_alarmes', 'User pode visualizar api_turno')),
                'managed': True,
            },
        ),
    ]
