# Generated by Django 4.2.4 on 2024-08-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField(max_length=8)),
                ('carro', models.CharField(max_length=2)),
                ('valor', models.FloatField()),
                ('medida', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'db_sensor',
                'managed': True,
                'unique_together': {('sensor', 'datetime', 'carro')},
            },
        ),
    ]
