# Generated by Django 4.2.4 on 2024-08-23 12:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas_API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da Empresa', max_length=150)),
                ('status', models.BooleanField(default=True, help_text='Status da Empresa')),
            ],
            options={
                'db_table': 'Empresas_API',
                'unique_together': {('nome',)},
            },
        ),
        migrations.CreateModel(
            name='Machines_API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_serie', models.CharField(help_text='Número de série da máquina (M00...)', max_length=10)),
                ('carros', models.IntegerField(default=0, help_text='Quantidade de carros')),
                ('modelo', models.CharField(help_text='Siga a nomenclatura CR, DC, SO...', max_length=5)),
                ('data_active', models.DateTimeField(default=datetime.datetime(2024, 8, 23, 9, 14, 6, 227548), help_text='Data de ativação da API')),
                ('status', models.BooleanField(default=1, help_text='Status da API dessa máquina')),
                ('empresa', models.ForeignKey(help_text='Empresa dona da máquina', on_delete=django.db.models.deletion.CASCADE, to='Usuario.empresas_api')),
            ],
            options={
                'db_table': 'Machine_com_API',
                'unique_together': {('n_serie',)},
            },
        ),
    ]
