# Generated by Django 4.2.4 on 2024-08-23 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_empresas_api_machines_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines_api',
            name='data_active',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 23, 9, 15, 7, 378851), help_text='Data de ativação da API'),
        ),
    ]
