# Generated by Django 4.2.4 on 2024-08-23 12:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Usuario', '0003_alter_machines_api_data_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlapi',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='controlapi',
            name='group_user_id',
        ),
        migrations.AddField(
            model_name='controlapi',
            name='group',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machines_api',
            name='data_active',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 23, 9, 55, 59, 449737), help_text='Data de ativação da API'),
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
    ]
