# Generated by Django 4.2.4 on 2024-08-23 14:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Usuario', '0004_rename_user_id_controlapi_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines_api',
            name='data_active',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 23, 11, 1, 14, 976205), help_text='Data de ativação da API'),
        ),
        migrations.CreateModel(
            name='User_Acess_Machines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.machines_api')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Usuarios_e_Machines_Access_API',
            },
        ),
    ]
