# Generated by Django 4.2.4 on 2024-08-23 14:11

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Usuario', '0005_alter_machines_api_data_active_user_acess_machines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines_api',
            name='data_active',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 23, 11, 11, 10, 421121), help_text='Data de ativação da API'),
        ),
        migrations.AlterUniqueTogether(
            name='user_acess_machines',
            unique_together={('user', 'machine')},
        ),
    ]
