# Generated by Django 4.2.4 on 2024-08-23 17:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Usuario', '0006_alter_machines_api_data_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines_api',
            name='data_active',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 23, 14, 25, 23, 987196), help_text='Data de ativação da API'),
        ),
        migrations.CreateModel(
            name='Token_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Token_user',
                'unique_together': {('user', 'token')},
            },
        ),
    ]
