# Generated by Django 4.2.4 on 2024-08-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorioresumido',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(blank=True, db_column='datetime', null=True)),
                ('carro', models.CharField(blank=True, db_column='Carro', max_length=2, null=True)),
                ('receita', models.CharField(blank=True, db_column='Receita', max_length=50, null=True)),
                ('datainicio', models.CharField(blank=True, db_column='DataInicio', max_length=50, null=True)),
                ('inicioforno', models.CharField(blank=True, db_column='InicioForno', max_length=50, null=True)),
                ('fimforno', models.CharField(blank=True, db_column='FimForno', max_length=50, null=True)),
                ('duracaoforno', models.CharField(blank=True, db_column='DuracaoForno', max_length=50, null=True)),
                ('sp_temperatura', models.FloatField(blank=True, db_column='SP_Temperatura', null=True)),
                ('fimciclo', models.CharField(blank=True, db_column='FimCiclo', max_length=50, null=True)),
                ('duracaociclo', models.CharField(blank=True, db_column='DuracaoCiclo', max_length=50, null=True)),
                ('cozidos', models.CharField(blank=True, db_column='Cozidos', max_length=50, null=True)),
                ('duracaoparada', models.CharField(blank=True, db_column='DuracaoParada', max_length=50, null=True)),
                ('gas', models.FloatField(blank=True, db_column='Gas', null=True)),
                ('energia', models.FloatField(blank=True, db_column='Energia', null=True)),
                ('indice', models.IntegerField(blank=True, db_column='Indice', null=True)),
                ('id_conjunto', models.IntegerField(blank=True, null=True)),
                ('id_receita', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'db_producao',
                'managed': True,
            },
        ),
    ]
