# Generated by Django 4.2.4 on 2024-08-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status_Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('timezone', models.CharField(max_length=80, null=True)),
            ],
            options={
                'db_table': 'db_status_machine',
            },
        ),
    ]
